/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 gamingKeyboard.glb 
Author: ZxTulz (https://sketchfab.com/zxtulz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-keyboard-c1e5e07153d84978a1ad7256d720220a
Title: Gaming keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GamingKeyboard(props) {
  const { nodes, materials } = useGLTF('./models/gamingKeyboard.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.085}>
        <mesh  castShadow receiveShadow  geometry={nodes['Plane004_13_-_Default_0'].geometry} material={materials['13_-_Default']} position={[7.95, 2.951, 2.749]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/gamingKeyboard.glb')
