/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 phone.glb 
Author: Levi (https://sketchfab.com/leviromano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samsung-phone-030019d343df47e598e929a785d1e749
Title: Samsung Phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Phone(props) {
  const { nodes, materials } = useGLTF('./models/phone.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['3dphoneuvmap_topface_0'].geometry} material={materials.topface} />
        <mesh geometry={nodes['3dphoneuvmap_lowerface_0'].geometry} material={materials.lowerface} />
        <mesh geometry={nodes['3dphoneuvmap_sides_0'].geometry} material={materials.sides} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/phone.glb')
